### ISSUE TITLE
rsyslog generates error Error relocating /lib/libuuid.so.1: getrandom: symbol not found

### ISSUE THREAD

**Issue by meauris** [voxxit/dockerfiles#12]
docker run -it rsyslog --name voxxit/rsyslog
returns
Error relocating /lib/libuuid.so.1: getrandom: symbol not found

**Comment by voxxit** [comment]
@meauris Please try again:
<img width="700" alt="Screen Shot 2022-01-11 at 1 13 24 PM" src="https://user-images.githubusercontent.com/12201/149022419-aadc893a-4e70-4e0b-9442-73a331597f4d.png">
