### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kaihendry** [voxxit/dockerfiles#4]
Sorry for the newb question.

I did a `docker pull voxxit/goaccess` and now I'm unsure how to bind goaccess to my host system (coreos) to simply run the command. Some docs typical usage docs would be nice.

Would be nice to see something upon https://hub.docker.com/r/voxxit/goaccess/ I wonder why the hub doesn't reference the Dockerfile ?!

**Comment by voxxit** [comment]
@kaihendry It is mostly because this was not one that was included in my dockerfiles repo, but rather `docker push`'d to Docker Hub :) Sorry about that!
